apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: payment-service
type: Opaque
stringData:
  # Common API Key
  COMMON_X_API_KEY: "change_this_to_a_secure_random_string"
  
  # Database
  POSTGRES_PASSWORD: "CHANGE_THIS_PASSWORD"
  DATABASE_URL: "postgresql://momo:CHANGE_THIS_PASSWORD@postgres-service:5432/momo_db?schema=public"
  
  # Redis
  REDIS_PASSWORD: "CHANGE_THIS_REDIS_PASSWORD"
  
  # JWT
  JWT_SECRET: "change_this_to_a_long_random_secret_min_32_chars_for_production"
  
  # MTN MoMo
  MTN_SUBSCRIPTION_KEY: "your_production_subscription_key"
  MTN_API_USER: "your_production_api_user"
  MTN_API_KEY: "your_production_api_key"
  MTN_BASE_URL: "https://sandbox.momodeveloper.mtn.com"
  
  # Admin
  ADMIN_EMAIL: "admin@yourdomain.com"
  ADMIN_PASSWORD: "CHANGE_THIS_STRONG_PASSWORD"
