apiVersion: v1
kind: ConfigMap
metadata:
  name: momo-config
  namespace: momo
data:
  NODE_ENV: "production"
  PORT: "3000"
  REDIS_HOST: "momo-redis-service"
  REDIS_PORT: "6379"
  JWT_EXPIRES_IN: "8h"
  THROTTLE_TTL: "60000"
  THROTTLE_LIMIT: "60"
  MTN_BASE_URL: "https://proxy.momoapi.mtn.com"
  MTN_ENVIRONMENT: "production"
  RUN_SEED: "false"
